### ISSUE TITLE
problem with pair

### ISSUE THREAD

**Issue by ZoltXs** [suborb/philips_android_tv#14]
Hello, have if someone can help me, when I try to pair, with my definition I get this error message

Mac-mini-de-Jb:/ jb$ python ./philips.py --host 172.168.0.182 pair
Traceback (most recent call last):
  File "./philips.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by svenove** [comment]
> Requests is not a built in module (does not come with the default python installation), so you will have to install it:
>
> **OSX/Linux**
> Use $ _sudo pip install requests_ if you have  _pip_ installed
>Alternatively you can also use _sudo easy_install -U requests_ if you have _easy_install_ installed.

From
https://stackoverflow.com/a/17309309

**Comment by ZoltXs** [comment]
Ya lo he solucionado gracias 👍🏻
