### ISSUE TITLE
"Forbidden" from http://ip:1925/6/pair/request

### ISSUE THREAD

**Issue by SebastianCallh** [suborb/philips_android_tv#30]
My philips 55oled754 does not want to cooperate on this one. I can see TV info on http://ip:1925/6/system but I consistently get "Forbidden" on http://ip:1925/6/pair/request. I have tried to set the TV in remote pairing mode as suggested [here](https://github.com/suborb/philips_android_tv/issues/25) but that doesn't do it either. Have someone here managed to use this repo with 55oled754?

**Comment by suborb** [comment]
The 55oled754 is a Saphi TV, as such this project isn't needed since no pairing is required.

Follow the comments from here: https://github.com/suborb/philips_android_tv/issues/26#issuecomment-633309367

**Comment by SebastianCallh** [comment]
Thank you for the quick response! And for the links. They were really helpful and now I understand what is going on. Have a good one!
