### ISSUE TITLE
Could not open requirements file

### ISSUE THREAD

**Issue by d0nY90** [suborb/philips_android_tv#34]
Hi,

i‘m new to all of this (homebridge, Python, Raspberry Pi...). I have to find out the API user and password of my Philips Android TV and I found this tool. I guess I don’t use it correctly. 

I opened the terminal in the homebridge Web UI and typed in: pip install -r requirements.txt and i get an error which says „could not open requirements file“. 

What’s the mistake ?

thanks for an answer and happy new year 
Daniel

**Comment by Staubgeborener** [comment]
You have to be in the directory where the requirements file of this project is placed.

Example:
```
git clone https://github.com/suborb/philips_android_tv
cd philips_android_tv
pip3 install -r requirements.txt
```

**Comment by d0nY90** [comment]
Thank you so much ! It worked.
